java_version=21
fabric_api_version=0.141.6+1.21.11
yacl_dependency=dev.isxander:yet-another-config-lib:3.8.2+1.21.11-fabric
yacl_min_version=3.8.2
modmenu_dependency=com.terraformersmc:modmenu:17.0.1
loader_version=0.19.3
loader_min_version=0.19
mapping_strategy=intermediary
source_strategy=legacy_render
screen_event=afterRender
