java_version=25
fabric_api_version=0.155.3+26.1.2
yacl_dependency=dev.isxander:yet-another-config-lib:3.9.4+26.1-fabric
yacl_min_version=3.9.4
modmenu_dependency=com.terraformersmc:modmenu:18.0.2
loader_version=0.19.3
loader_min_version=0.19
mapping_strategy=official
source_strategy=native
screen_event=afterExtract
