java_version=25
fabric_api_version=0.157.0+26.2
yacl_dependency=dev.isxander:yet-another-config-lib:3.9.4+26.2-fabric
yacl_min_version=3.9.4
modmenu_dependency=com.terraformersmc:modmenu:20.0.1
loader_version=0.19.3
loader_min_version=0.19
mapping_strategy=official
source_strategy=native
screen_event=afterForeground
