java_version=25
loader_version=0.19.5
fabric_api_version=0.161.0+26.3
yacl_dependency=maven.modrinth:yacl:s9SjoFu1
yacl_min_version=3.9.7
modmenu_dependency=maven.modrinth:modmenu:kyy7dbrZ
loader_min_version=0.19.5
mapping_strategy=official
source_strategy=native
screen_event=afterForeground
